In [17]:
import numpy as np

In [18]:
data = np.random.randn(2,5)

In [19]:
data

array([[-0.02271408,  1.38265167, -0.42732563,  0.94944851, -1.08342414],
       [ 2.01746616, -0.83819388, -0.34447173, -0.24210366,  0.06659675]])

In [20]:
data * 10

array([[ -0.2271408 ,  13.82651669,  -4.27325628,   9.49448506,
        -10.83424135],
       [ 20.17466162,  -8.38193883,  -3.44471726,  -2.42103659,
          0.66596753]])

In [21]:
data + data


array([[-0.04542816,  2.76530334, -0.85465126,  1.89889701, -2.16684827],
       [ 4.03493232, -1.67638777, -0.68894345, -0.48420732,  0.13319351]])

In [22]:
data + 10

array([[ 9.97728592, 11.38265167,  9.57267437, 10.94944851,  8.91657586],
       [12.01746616,  9.16180612,  9.65552827,  9.75789634, 10.06659675]])

In [23]:
data.shape

(2, 5)

In [24]:
z = [1,2,3,4,56]

In [25]:
zarray = np.array(z)

In [26]:
zarray

array([ 1,  2,  3,  4, 56])

In [27]:
z = np.arange(90)
z

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89])

In [28]:
z_slice = z[0:50:2]
z_slice

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [29]:
z_slice[0] = 666
z_slice[0:10]

array([666,   2,   4,   6,   8,  10,  12,  14,  16,  18])

In [30]:
z_slice[:] = 40
z_slice

array([40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40,
       40, 40, 40, 40, 40, 40, 40, 40])

In [31]:
arr2d = np.array([[0,1,2], [3,4,5],[6,7,8]])
arr2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [67]:
print(arr2d[:, :1])
print('-----------')
print(arr2d[:, :3])
print('-----------')
arr2d[:2, 1:] = 0
print(arr2d[:2, 1:])

[[0]
 [3]
 [6]]
-----------
[[0 0 0]
 [3 0 0]
 [6 7 8]]
-----------
[[0 0]
 [0 0]]


names = np.array(['Jacaré', 'Serpente', 'Lagarto','Ophiophagus', 'Axolote'])

In [48]:
arr2d[:2]

array([[0, 1, 2],
       [3, 4, 5]])

In [39]:
print(arr2d[2])
print(arr2d[2][2])
print(arr2d[2,2])

[6 7 8]
8
8


In [41]:
arr3d = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [43]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
x = arr3d[1]
x

array([[ 7,  8,  9],
       [10, 11, 12]])

In [73]:
animals = np.array(['Jacaré', 'Lagarto', 'Axolote', 'Serpente', 'Jacaré'])
data = np.random.randn(7,4)
print(animals == 'Jacaré')
print(animals != 'Jacaré')

[ True False False False  True]
[False  True  True  True False]


In [74]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
print(arr)

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]


In [77]:
arr =  np.arange(32).reshape((8,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])