In [1]:
import numpy as np

In [2]:
zzz = np.array([1,2,3,4,5,6])
zzz

array([1, 2, 3, 4, 5, 6])

In [8]:
yyy = np.arange(16).reshape((2,2,4))
yyy

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [9]:
yyy.transpose((1,0,2))
yyy

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [11]:
yyy.swapaxes(1,2)
yyy

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [17]:
zzz = np.arange(11)
np.sqrt(zzz)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [18]:
np.exp(zzz)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [27]:
z = np.random.randint(100)
z

95

In [28]:
y = np.random.randint(100)
y

19

In [29]:
np.maximum(z,y)

95

In [43]:
zzz = np.random.randn(10) * 8
zzz

array([  1.69943894,   4.40665093,   7.13606603,   0.18352369,
       -10.88106143,   1.06067669,  -6.00945583,  -4.82848867,
       -12.45372448, -11.10683197])

In [44]:
remainder, whole_part = np.modf(zzz)

In [45]:
remainder

array([ 0.69943894,  0.40665093,  0.13606603,  0.18352369, -0.88106143,
        0.06067669, -0.00945583, -0.82848867, -0.45372448, -0.10683197])

In [46]:
whole_part

array([  1.,   4.,   7.,   0., -10.,   1.,  -6.,  -4., -12., -11.])

In [47]:
zzz

array([  1.69943894,   4.40665093,   7.13606603,   0.18352369,
       -10.88106143,   1.06067669,  -6.00945583,  -4.82848867,
       -12.45372448, -11.10683197])

In [48]:
np.sqrt(zzz)

C:\Users\jojos\AppData\Local\Temp\ipykernel_6612\1441180435.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(zzz)


array([1.30362531, 2.09920245, 2.67134162, 0.42839665,        nan,
       1.02989159,        nan,        nan,        nan,        nan])

In [49]:
np.sqrt(zzz,zzz)

C:\Users\jojos\AppData\Local\Temp\ipykernel_6612\2851518010.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(zzz,zzz)


array([1.30362531, 2.09920245, 2.67134162, 0.42839665,        nan,
       1.02989159,        nan,        nan,        nan,        nan])