In [28]:
import numpy as np
import pandas as pd

In [29]:
a = [1,2,3]
np.array(a)
a

[1, 2, 3]

In [30]:
a = [[1,2,3] ,[4,5,6]]
np.array(a, dtype = np.float32)
a

[[1, 2, 3], [4, 5, 6]]

In [32]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [33]:
np.random.randint(low = 3, high= 9, size= 3)

array([8, 8, 3])

In [34]:
np.random.random(size= 4)

array([0.48355796, 0.55006549, 0.93269745, 0.84790706])

In [35]:
s = pd.Series([1,2,3,4], name = "col")
np.array(s)

#Generate NumPy Array from a Pandas Series

array([1, 2, 3, 4], dtype=int64)

In [39]:
a = np.arange(36)
a.reshape((6,6))
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35])

In [47]:
z = np.array([[1,2],[3,4]])
x = np.array([[5,6],[7,8]])
print(np.concatenate((x,z), axis =1)) #horizontal = np.hstack()
print('------------')
print(np.concatenate((x,z), axis=0)) #vertical = np.vstack()
print('------------')
print(np.concatenate((x,y), axis=None))

[[5 6 1 2]
 [7 8 3 4]]
------------
[[5 6]
 [7 8]
 [1 2]
 [3 4]]
------------
[5 6 7 8 <map object at 0x0000019C6BC7D5E0>]


In [49]:
a = np.array([1,2,3,4,1,4,2,3,8,9])
np.unique(a)
np.unique(a, axis =0) # rows
np.unique(a, axis =1) # column

array([1, 2, 3, 4, 8, 9])

### Mathematical Operations

In [53]:
a = np.array([180])
print("Trigonometric Sine   :", np.sin(a))
print("Trigonometric Cosine :", np.cos(a))
print("Trigonometric Tangent:", np.tan(a))

Trigonometric Sine   : [-0.80115264]
Trigonometric Cosine : [-0.59846007]
Trigonometric Tangent: [1.33869021]


In [60]:
z = np.linspace(30,70,10)
print(z)
print('------------------')
print(np.floor(z))
print('------------------')
print(np.ceil(z))
print('------------------')
print(np.rint(z))
print('------------------')
print(np.round(z,2))


[30.         34.44444444 38.88888889 43.33333333 47.77777778 52.22222222
 56.66666667 61.11111111 65.55555556 70.        ]
------------------
[30. 34. 38. 43. 47. 52. 56. 61. 65. 70.]
------------------
[30. 35. 39. 44. 48. 53. 57. 62. 66. 70.]
------------------
[30. 34. 39. 43. 48. 52. 57. 61. 66. 70.]
------------------
[30.   34.44 38.89 43.33 47.78 52.22 56.67 61.11 65.56 70.  ]


In [66]:
#Exponents and Logarithms
z = np.arange(2,11)
print(z)
print('--------------------------')
print(np.exp(z).round(2))
print('--------------------------')
print(np.log(z).round(2))





[ 2  3  4  5  6  7  8  9 10]
--------------------------
[7.390000e+00 2.009000e+01 5.460000e+01 1.484100e+02 4.034300e+02
 1.096630e+03 2.980960e+03 8.103080e+03 2.202647e+04]
--------------------------
[0.69 1.1  1.39 1.61 1.79 1.95 2.08 2.2  2.3 ]


In [74]:
#Sum product
zz = np.array([1,2,3,4,5,6])
print(np.sum(zz))
zzz =  np.prod(zz)
print(zzz)
print(np.sqrt(zzz).round(2))

21
720
26.83


## Matrix and Vector Operator

In [76]:
#Dot product
z = np.array([[1, 2], [3, 4]])
y = np.array([[1, 1], [1, 1]])
np.dot(x, y)

array([[11, 11],
       [15, 15]])

In [80]:
#matrix product
a = np.array([[1, 2], [3, 4]])
b = np.array([[1, 1], [1, 1]])
print(np.matmul(a, b))
print("------------")
print(a@b)
 

[[3 3]
 [7 7]]
------------
[[3 3]
 [7 7]]


In [82]:
#vector norm
a = np.arange(-4, 5)
print(np.linalg.norm(a))
print('________________')
print(np.linalg.norm(a, 1))

7.745966692414834
________________
20.0


###  Searching Methods

In [90]:
z = np.random.randint(-10,10,10) 

np.where(z < 0, 0, z)
#bigger than 0

array([0, 0, 1, 0, 9, 8, 0, 0, 9, 3])

### Statistical Methods

In [97]:
#mean
zzz = np.array([1,2,3,4,5])
print(np.mean(zzz))
xyz = np.array([[1,2,3], [8,7,10]])
print(np.mean(xyz, axis =0))
print(np.mean(xyz, axis =1))

3.0
[4.5 4.5 6.5]
[2.         8.33333333]


In [100]:
#median
print(np.median(zzz))
print(np.median(xyz, axis =0))
print(np.median(xyz, axis = 1))

3.0
[4.5 4.5 6.5]
[2. 8.]


In [103]:
#standard deviation
a = np.array([[1, 2], [3, 4]])
print(np.std(a))
print(np.std(a, axis = 1))
print(np.std(a, axis = 0))

1.118033988749895
[0.5 0.5]
[1. 1.]
